Updated Buildspec

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -2,7 +2,7 @@ version: 0.2
 
 env:
   secrets-manager:
-    # IMPORT SECRETS FROM SECRETS MANAGER  
+    # IMPORT SECRETS FROM SECRETS MANAGER
     SONAR_TOKEN: "ike-fitness-secrets:SONAR_TOKEN"
     SNYK_TOKEN: "ike-fitness-secrets:SNYK_TOKEN"
     SONAR_PROJECT_KEY: "ike-fitness-secrets:SONAR_PROJECT_KEY"
@@ -20,26 +20,26 @@ phases:
       nodejs: latest
     commands:
       # INSTALL TOOLS AND DEPENDENCIES
-      - apt-get -y update 
+      - apt-get -y update
       - sleep 10
       - npm install
       - npm install -g aws-cli
       - npm install -g sonarqube-scanner
       - npm install -g snyk
-      - npm install -g snyk-to-html 
+      - npm install -g snyk-to-html
       - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/kubectl
       - chmod +x ./kubectl
       - mv ./kubectl /usr/local/bin/kubectl
       - apt-get install -y jq
       - sleep 10
-      - if ! command -v bc &> /dev/null; 
-        then 
-          apt-get install -y bc; 
-        fi 
+      - if ! command -v bc &> /dev/null;
+        then
+        apt-get install -y bc;
+        fi
 
   pre_build:
     commands:
-      # PERFORM QUALITY TEST WITH SONARCLOUD 
+      # PERFORM QUALITY TEST WITH SONARCLOUD
       - sleep 10
       - echo "Runnning quality test with SonarCloud......."
       - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_ORGANIZATION_KEY
@@ -50,16 +50,16 @@ phases:
       - SONAR_PROJECT_STATUS=$(echo $SONAR_RESULT | jq -r '.projectStatus.status')
 
         # Fail the pipeline if code fails the set quality gates
-      - if [ "$SONAR_PROJECT_STATUS" = "ERROR" ]; 
-        then 
-          echo "SonarCloud Quality Gate check failed. Exiting with an error."; 
-          exit 1; 
-        else 
-          echo "SonarCloud Quality Gate check passed."; 
+      - if [ "$SONAR_PROJECT_STATUS" = "ERROR" ];
+        then
+        echo "SonarCloud Quality Gate check failed. Exiting with an error.";
+        exit 1;
+        else
+        echo "SonarCloud Quality Gate check passed.";
         fi
       - sleep 10
 
-      # PERFORM BOTH SCA AND SAST WITH SNYK 
+      # PERFORM BOTH SCA AND SAST WITH SNYK
       - echo "Running SAST and SCA test with Snyk........."
       - SNYK_TOKEN=$SNYK_TOKEN
 
@@ -70,45 +70,45 @@ phases:
       - SNYK_OPEN_SOURCE_SEVERITY=$(jq -r '.vulnerabilities[0].severity' snyk_open_source.json)
       - SNYK_OPEN_SOURCE_cvssScore=$(jq -r '.vulnerabilities[0].cvssScore' snyk_open_source.json)
 
-         # Fail build only on cvss 7 and above
-      - if [ "$(echo "$SNYK_OPEN_SOURCE_cvssScore >= 7" | bc)" -eq 1 ]; 
-        then 
-          echo "cvssScore is greater than 7. Exiting with an error.";
-          exit 1; 
+        # Fail build only on cvss 7 and above
+      - if [ "$(echo "$SNYK_OPEN_SOURCE_cvssScore >= 7" | bc)" -eq 1 ];
+        then
+        echo "cvssScore is greater than 7. Exiting with an error.";
+        exit 1;
         fi
 
-         # Continue build with a warning if severity is medium
-      - if [ "$SNYK_OPEN_SOURCE_SEVERITY" = "medium" ]; 
-        then 
-          echo "There are many vulnerabilities, but continuing. Pay attention to snyk_open_source.html for details";
+        # Continue build with a warning if severity is medium
+      - if [ "$SNYK_OPEN_SOURCE_SEVERITY" = "medium" ];
+        then
+        echo "There are many vulnerabilities, but continuing. Pay attention to snyk_open_source.html for details";
         fi
-      - sleep 10  
+      - sleep 10
 
-        # Run Static Application Security Test with snyk code test 
-      - echo "Running Code Scan (SAST)......." 
+        # Run Static Application Security Test with snyk code test
+      - echo "Running Code Scan (SAST)......."
       - snyk code test --all-projects --json-file-output=snyk_code_test.json --fail-on=patchable || true # Prevent snyk from exiting if issues are discovered. Handle the decision yourself..
       - snyk-to-html -i snyk_code_test.json -o snyk_code_test.html # Get a html artifact of the result
 
-        # Fail if there are patchable errors on the code itself
-      - if jq '.runs[].tool.driver.rules[] | select(.defaultConfiguration.level == "error")' snyk_code_test.json; 
-        then
-          echo "Patchable errors found in code. Exiting with an error."; 
-          exit 1; 
-        else 
-          echo "No significant errors found. Continuing with the build."; 
-        fi
-      - sleep 10 
 
+        # Fail if there are patchable errors on the code itself
+      - if jq '.runs[].tool.driver.rules[] | select(.defaultConfiguration.level == "error")' snyk_code_test.json;
+        then
+        echo "Patchable errors found in code. Exiting with an error.";
+        exit 1;
+        else
+        echo "No significant errors found. Continuing with the build.";
+        fi
+      - sleep 10
 
   build:
     commands:
-      # BUILD CODE, DOCKERIZE IT, AND PUSH DOCKER IMAGE TO AWS ECR REPOSITORY 
-        # Build app 
+      # BUILD CODE, DOCKERIZE IT, AND PUSH DOCKER IMAGE TO AWS ECR REPOSITORY
+      # Build app
       - echo "Building the NodeJS App......."
       - npm run build:js
       - sleep 5
 
-        # Create a docker image 
+        # Create a docker image
       - echo "Creating a docker image..........."
       - echo "Logging in to Amazon ECR..."
       - aws --version
@@ -125,21 +125,21 @@ phases:
   post_build:
     commands:
       # DEPLOY TO EKS AND RUN DYNAMIC APPLICATION SECURITY TEST (DAST)
-        # Deploy to EKS 
-      - echo "Deploying Docker image to EKS......." 
+      # Deploy to EKS
+      - echo "Deploying Docker image to EKS......."
       - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name ike-eks-cluster
       - cat ~/.kube/config
       - sleep 5
 
         # Check if ikefitness namespace already exists, and create it if it doesn't
       - echo "Checking namespace....."
-      - NAMESPACE=$(kubectl get namespace | grep ikefitness || true) # In the first build, this will return false so it needs to be protected from failing. 
-      - if [ -z "$NAMESPACE" ]; 
-        then 
-          echo "Creating ikefitness namespace"
-          kubectl create namespace ikefitness; 
+      - NAMESPACE=$(kubectl get namespace | grep ikefitness || true) # In the first build, this will return false so it needs to be protected from failing.
+      - if [ -z "$NAMESPACE" ];
+        then
+        echo "Creating ikefitness namespace"
+        kubectl create namespace ikefitness;
         else
-          echo "ikefitness namespace already exists";
+        echo "ikefitness namespace already exists";
         fi
       - sleep 5
 
@@ -147,13 +147,14 @@ phases:
       - echo "Checking regcred secret....."
       - SECRET=$(kubectl get secret -n ikefitness | grep regcred || true) # In the first build, this will return false so it needs to be protected from failing.
 
-         # This secret is required to pull images from private repositories like ECR 
+
+        # This secret is required to pull images from private repositories like ECR
       - if [ -z "$SECRET" ];
-        then 
-          echo "Creating regcred secret......"
-          kubectl create secret docker-registry regcred -n ikefitness --docker-server=$DOCKER_SERVER --docker-username=$DOCKER_USERNAME --docker-password=$DOCKER_PASSWORD --docker-email=$DOCKER_EMAIL; 
-        else 
-          echo "regcred secret already exists";
+        then
+        echo "Creating regcred secret......"
+        kubectl create secret docker-registry regcred -n ikefitness --docker-server=$DOCKER_SERVER --docker-username=$DOCKER_USERNAME --docker-password=$DOCKER_PASSWORD --docker-email=$DOCKER_EMAIL;
+        else
+        echo "regcred secret already exists";
         fi
       - sleep 5
 
@@ -164,35 +165,35 @@ phases:
 
         # Check if load balancer already exists and create it if it doesn't
       - LOADBALANCER=$(kubectl get service ikefitness-service -n ikefitness --output='json' --ignore-not-found | awk -F'"' '/hostname/{print $4}') # In the first build, this will return false so it needs to be protected from failing.
-      - if [ -z "$LOADBALANCER" ]; 
-        then 
-          echo "Creating load balancer......"
-          kubectl apply -f service.yaml -n ikefitness; 
+      - if [ -z "$LOADBALANCER" ];
+        then
+        echo "Creating load balancer......"
+        kubectl apply -f service.yaml -n ikefitness;
         else
-          echo "Load balancer $LOADBALANCER already exists";
+        echo "Load balancer $LOADBALANCER already exists";
         fi
       - echo "Deployment completed..........."
       - sleep 50
 
-        # Perform Dynamic Application Security Test with OWASP ZAP 
+        # PERFORM DAST WITH OWASP ZAP
       - echo "Running DAST with OWASP ZAP........."
       - docker pull softwaresecurityproject/zap-stable
       - chmod a+w $(pwd)
 
         # At this stage of the pipeline, the code has alrady been deployed, so there is no point failing build if DAST finds vulnerabilities. So the scans a protected, so the results can be collected for all scans
-        # This test performs baseline scan and api scan on all the api endpoints in Ike Fitness App. 
+        # This test performs baseline scan and api scan on all the api endpoints in Ike Fitness App.
 
       - docker run -v $(pwd):/zap/wrk/:rw -t softwaresecurityproject/zap-stable zap-baseline.py -t http://$LOADBALANCER -g gen.conf -r baseline_scan.html || true
-      - sleep 20 
-      - docker run -v $(pwd):/zap/wrk/:rw -t softwaresecurityproject/zap-stable zap-api-scan.py -t http://$LOADBALANCER/api/v1/plans -f openapi -g gen.conf -r plans_endpoint.html || true 
       - sleep 20
-      - docker run -v $(pwd):/zap/wrk/:rw -t softwaresecurityproject/zap-stable zap-api-scan.py -t http://$LOADBALANCER/api/v1/users -f openapi -g gen.conf -r users_endpoint.html || true 
+      - docker run -v $(pwd):/zap/wrk/:rw -t softwaresecurityproject/zap-stable zap-api-scan.py -t http://$LOADBALANCER/api/v1/plans -f openapi -g gen.conf -r plans_endpoint.html || true
       - sleep 20
-      - docker run -v $(pwd):/zap/wrk/:rw -t softwaresecurityproject/zap-stable zap-api-scan.py -t http://$LOADBALANCER/api/v1/reviews -f openapi -g gen.conf -r reviews_endpoint.html || true 
-      - sleep 20 
-      - docker run -v $(pwd):/zap/wrk/:rw -t softwaresecurityproject/zap-stable zap-api-scan.py -t http://$LOADBALANCER/api/v1/bookings -f openapi -g gen.conf -r bookings_endpoint.html || true 
-      - sleep 20 
- 
+      - docker run -v $(pwd):/zap/wrk/:rw -t softwaresecurityproject/zap-stable zap-api-scan.py -t http://$LOADBALANCER/api/v1/users -f openapi -g gen.conf -r users_endpoint.html || true
+      - sleep 20
+      - docker run -v $(pwd):/zap/wrk/:rw -t softwaresecurityproject/zap-stable zap-api-scan.py -t http://$LOADBALANCER/api/v1/reviews -f openapi -g gen.conf -r reviews_endpoint.html || true
+      - sleep 20
+      - docker run -v $(pwd):/zap/wrk/:rw -t softwaresecurityproject/zap-stable zap-api-scan.py -t http://$LOADBALANCER/api/v1/bookings -f openapi -g gen.conf -r bookings_endpoint.html || true
+      - sleep 20
+
 artifacts:
   files: "**/*"
   name: ike-$CODEBUILD_BUILD_NUMBER-$(date "+%Y-%m-%d %H:%M")
